"""Create food and exercise tables

Revision ID: b48d94ac46c3
Revises: c4eb2361224d
Create Date: 2026-01-01 02:41:45.260176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b48d94ac46c3'
down_revision: Union[str, Sequence[str], None] = 'c4eb2361224d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID bài tập'),
    sa.Column('owner_user_id', sa.UUID(), nullable=True, comment='NULL = global data, có giá trị = custom của user'),
    sa.Column('activity_code', sa.Text(), nullable=True, comment='Mã hoạt động từ dataset'),
    sa.Column('major_heading', sa.Text(), nullable=True, comment='Nhóm bài tập chính (vd: Running, Swimming)'),
    sa.Column('description', sa.Text(), nullable=False, comment='Mô tả bài tập'),
    sa.Column('met_value', sa.Numeric(precision=6, scale=2), nullable=False, comment='Giá trị MET (Metabolic Equivalent) - năng lượng tiêu hao'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm tạo record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm cập nhật record'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercises_owner_user_id_description', 'exercises', ['owner_user_id', 'description'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_exercises_activity_code_global_active', 'exercises', ['activity_code'], unique=True, postgresql_where=sa.text('owner_user_id IS NULL AND deleted_at IS NULL AND activity_code IS NOT NULL'))
    
    op.create_table('foods',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID thực phẩm'),
    sa.Column('owner_user_id', sa.UUID(), nullable=True, comment='NULL = global data, có giá trị = custom của user'),
    sa.Column('source_code', sa.Text(), nullable=True, comment='Mã nguồn từ dataset (vd: 01001)'),
    sa.Column('name', sa.Text(), nullable=False, comment='Tên thực phẩm'),
    sa.Column('food_group', sa.Text(), nullable=True, comment='Nhóm thực phẩm (vd: Dairy, Meat)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm tạo record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm cập nhật record'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_foods_owner_user_id_name', 'foods', ['owner_user_id', 'name'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_foods_source_code_global', 'foods', ['source_code'], unique=True, postgresql_where=sa.text('owner_user_id IS NULL'))
    
    op.create_table('food_nutrients',
    sa.Column('food_id', sa.BigInteger(), nullable=False, comment='FK tới foods.id'),
    sa.Column('nutrient_name', sa.Text(), nullable=False, comment='Tên chất dinh dưỡng (vd: calories, protein)'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='Đơn vị của chất dinh dưỡng (vd: kcal, g, mg)'),
    sa.Column('amount_per_100g', sa.Numeric(precision=14, scale=6), nullable=False, comment='Lượng chất dinh dưỡng trên 100g'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm tạo record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm cập nhật record'),
    sa.CheckConstraint('amount_per_100g >= 0', name='ck_food_nutrients_amount_nonneg'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('food_id', 'nutrient_name')
    )
    op.create_index('ix_food_nutrients_food_id', 'food_nutrients', ['food_id'], unique=False)
    op.create_table('food_portions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID portion'),
    sa.Column('food_id', sa.BigInteger(), nullable=False, comment='FK tới foods.id'),
    sa.Column('amount', sa.Numeric(precision=10, scale=3), nullable=False, comment='Số lượng (vd: 1, 0.5)'),
    sa.Column('unit', sa.Text(), nullable=False, comment='Đơn vị (vd: cup, tbsp, piece)'),
    sa.Column('grams', sa.Numeric(precision=10, scale=3), nullable=False, comment='Quy đổi ra grams'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm tạo record'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm cập nhật record'),
    sa.CheckConstraint('amount > 0', name='ck_food_portions_amount_pos'),
    sa.CheckConstraint('grams > 0', name='ck_food_portions_grams_pos'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_food_portions_food_id', 'food_portions', ['food_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_food_portions_food_id', table_name='food_portions')
    op.drop_table('food_portions')
    op.drop_index('ix_food_nutrients_food_id', table_name='food_nutrients')
    op.drop_table('food_nutrients')

    op.drop_index('uq_foods_source_code_global', table_name='foods', postgresql_where=sa.text('owner_user_id IS NULL'))
    op.drop_index('ix_foods_owner_user_id_name', table_name='foods', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('foods')
    op.drop_index('uq_exercises_activity_code_global_active', table_name='exercises', postgresql_where=sa.text('owner_user_id IS NULL AND deleted_at IS NULL AND activity_code IS NOT NULL'))
    op.drop_index('ix_exercises_owner_user_id_description', table_name='exercises', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('exercises')

    # ### end Alembic commands ###
