"""Add biometrics_logs table

Revision ID: c4eb2361224d
Revises: 001_create_auth_tables
Create Date: 2025-12-31 02:36:54.462071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4eb2361224d'
down_revision: Union[str, Sequence[str], None] = '001_create_auth_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometrics_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID log'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK tới users.id'),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm đo (client gửi)'),
    sa.Column('weight_kg', sa.Float(), nullable=False, comment='Cân nặng (kg)'),
    sa.Column('height_cm', sa.Float(), nullable=False, comment='Chiều cao (cm)'),
    sa.Column('bmi', sa.Float(), nullable=False, comment='Chỉ số BMI (tính toán từ cân nặng và chiều cao)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm tạo record (server set)'),
    sa.CheckConstraint('height_cm IS NULL OR height_cm > 0', name='check_height_positive'),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg > 0', name='check_weight_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_biometrics_logs_user_id_logged_at', 'biometrics_logs', ['user_id', 'logged_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_biometrics_logs_user_id_logged_at', table_name='biometrics_logs')
    op.drop_table('biometrics_logs')
    # ### end Alembic commands ###